version: "3.6"
networks:
  net:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
services:
  logstash1:
    image: logstash:6.6.2
    hostname: logstash
    networks:
      - net
    deploy:
      placement:
        constraints: [node.labels.elk == 1]
      restart_policy:
        condition: on-failure
    volumes:
      - /opt/logstash/conf/:/opt/logstash/conf/
      - /var/log/logstash:/opt/logstash/logs
      - /var/deploy/logstash/conf/GeoLite2-City.mmdb:/opt/GeoLite2-City.mmdb