version: "3.6"
networks:
  net:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16

services:
  zk1:
    image: zookeeper:3.4.10
    hostname: zk1
    environment:
        - MYID=1
        - ZOO_SERVERS=server.1=zk1:2888:3888  server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - net
    deploy:
      placement:
        constraints: [node.labels.elk == 1]
      restart_policy:
        condition: on-failure
    ports:
      - '2181:2181'
    volumes:
      - /var/log/zookeeper:/data/zookeeper/log
      - /var/deploy/zookeeper/data:/data/zookeeper/data

  zk2:
    image: zookeeper:3.4.10
    hostname: zk2
    environment:
        - MYID=2
        - ZOO_SERVERS=server.1=zk1:2888:3888  server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - net
    deploy:
      placement:
        constraints: [node.labels.elk == 2]
      restart_policy:
        condition: on-failure
    volumes:
      - /var/log/zookeeper:/data/zookeeper/log
      - /var/deploy/zookeeper/data:/data/zookeeper/data

  zk3:
    image: zookeeper:3.4.10
    hostname: zk3
    environment:
        - MYID=3
        - ZOO_SERVERS=server.1=zk1:2888:3888  server.2=zk2:2888:3888 server.3=zk3:2888:3888
    networks:
      - net
    deploy:
      placement:
        constraints: [node.labels.elk == 3]
      restart_policy:
        condition: on-failure
    volumes:
      - /var/log/zookeeper:/data/zookeeper/log
      - /var/deploy/zookeeper/data:/data/zookeeper/data